services:
  - type: web
    name: alumniai-web
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput --settings=alumni_platform.settings.prod
    preDeployCommand: python manage.py migrate --noinput --settings=alumni_platform.settings.prod
    startCommand: daphne -b 0.0.0.0 -p $PORT alumni_platform.asgi:application
    envVars:
      - key: ENVIRONMENT
        value: prod
      - key: DJANGO_SETTINGS_MODULE
        value: alumni_platform.settings.prod
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          name: alumniai-redis
          type: redis
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: '587'
      - key: EMAIL_USE_TLS
        value: 'True'
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false

  - type: redis
    name: alumniai-redis
    plan: free
    ipAllowList: []
