# Generated by Django 4.2.26 on 2026-07-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationpreference_email_admin_broadcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('general', 'General'), ('session', 'Session'), ('referral', 'Referral'), ('payment', 'Payment'), ('verification', 'Verification'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('new_booking', 'New Booking'), ('session_cancelled_by_host', 'Session Cancelled by Host'), ('referral_applied', 'Referral Applied'), ('payout', 'Payout'), ('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted')], default='general', max_length=40),
        ),
    ]
